sql-bi/Bravo

- src/Bravo.csproj
- src/Infrastructure/Helpers/VpaxToolsHelper.cs
- Updated VertiPaqAnalyzer to 1.2.3
> Export VPAX - included Model.bim and DaxVpaView.json

- src/Infrastructure/Helpers/ConnectionStringHelper.cs
- src/Infrastructure/Messages/AppInstanceStartupMessage.cs
- src/Infrastructure/Services/ConnectionWrapper.cs
- src/Models/PBICloudDataset.cs
- Added PBICloudDataset.ExternalDatabaseName property
> Fix dataset name/id connection error

- src/Infrastructure/Extensions/StringExtensions.cs
- src/Infrastructure/Helpers/CommonHelper.cs
- src/Infrastructure/Helpers/ExceptionHelper.cs
- src/Infrastructure/Helpers/WebView2Helper.cs
- src/Models/FormatDax/FormatDaxRequest.cs
- Fixed incorrect value for `DaxLineBreakStyle.Auto`
- Improved `BravoUnexpectedException` error message
> Fix BravoUnexpectedException for DaxLineBreakStyle.Auto value

- src/Controllers/ApplicationController.cs
- src/Infrastructure/Helpers/ProcessHelper.cs
- src/Infrastructure/Services/ConnectionWrapper.cs
- src/Models/PBIDesktopReport.cs
- Added api/PBIDesktopOpenPBIX to replace StartPBIDesktopFromPBIX
- Fixed TabularConnectionWrapper.Dispose NullReferenceException (issue from telemetry)
> Added api/PBIDesktopOpenPBIX, fix NRE

- installer/wix/src/Bravo/Bravo-perUser.wxs
- installer/wix/src/Bravo/Bravo.wxs
'NOT WIX_UPGRADE_DETECTED' must used instead of 'NOT Installed'
> Fix installer Default*REMEMBER SetProperty condition

- src/Scripts/model/i18n/pt.ts
Hi!
I hope you're well.
Here's my little contribution.
How are national variations of the same language thinking?
These texts are in Portuguese from Portugal (pt/pt-pt)
For Brazilian Portuguese (pt-br) some terms are different.
> Update Portuguese translation

- src/Infrastructure/Helpers/ConnectionStringHelper.cs
Forced a valid `LocaleIdentifier` param to the connection string to avoid a `CultureNotFoundException` when the param is not provided and the ADOMD.NET provider uses the CurrentThread.CurrentUICulture.LCID. If the CurrentThread.CurrentUICulture.LCID is a LOCALE_CUSTOM_UNSPECIFIED locale then the `CultureNotFoundException` is raised
> Fixed CultureNotSupportedException for LOCALE_CUSTOM_UNSPECIFIED

- src/Infrastructure/Extensions/StringExtensions.cs
- src/Models/ExportData/ExportDataSettings.cs
- src/Services/ExportDataService.cs
To support export CSV in a subfolder #92
> Added ExportDelimitedTextSettings.CreateSubfolder property

- src/Infrastructure/Helpers/ConnectionStringHelper.cs
- src/Models/PBICloudDataset.cs
- added `PBICloudDataset.ExternalServerName`
> Fixed dataset connection from ExternalTool

- src/Assets/ManageDates/Templates/HolidaysDefinition.json
See https://github.com/sql-bi/DaxTemplate/pull/18
> Update JP/Sports Day in HolidaysDefinition

- src/Bravo.csproj
- test/Bravo.Tests/Bravo.Tests.csproj
- Removed Swagger private assets 
- Removed satellite resource
> Reduced app size

- src/Controllers/ApplicationController.cs
- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/AppExceptions.cs
- src/Infrastructure/Configuration/Settings/UserSettings.cs
- src/Infrastructure/Extensions/CommonExtensions.cs
- src/Infrastructure/Extensions/HostingExtensions.cs
- src/Infrastructure/Extensions/RegistryExtensions.cs
- src/Infrastructure/Helpers/CommonHelper.cs
- src/Infrastructure/Helpers/NotificationHelper.cs
- src/Infrastructure/Security/Policies/ADMX/bravo.admx
- src/Infrastructure/Security/Policies/ADMX/en-US/bravo.adml
- src/Infrastructure/Security/Policies/ADMX/en-US/sqlbi.adml
- src/Infrastructure/Security/Policies/ADMX/sqlbi.admx
- src/Infrastructure/Security/Policies/GroupPolicyManager.cs
- src/Infrastructure/Security/Policies/PolicyStatus.cs
- src/Models/BravoOptions.cs
- test/Bravo.Tests/Infrastructure/Extensions/CommonExtensionsTests.cs
- Added UserSettings.UpdateCheckEnabled
- Added group policy ADMX template
> Added update notification and channel policy

- src/Controllers/ApplicationController.cs
- src/Infrastructure/AppWindow.cs
- src/Infrastructure/Helpers/ProcessHelper.cs
- src/Infrastructure/Services/ConnectionWrapper.cs
- src/Infrastructure/Services/PowerBI/PBICloudAuthenticationService.cs
- Added `api/OpenControlPanelItem`
> Fix MSAL cross-thread exception

- src/Scripts/model/i18n/cz.ts
- src/Scripts/model/i18n/da.ts
- src/Scripts/model/i18n/de.ts
- src/Scripts/model/i18n/en.ts
- src/Scripts/model/i18n/es.ts
- src/Scripts/model/i18n/fr.ts
- src/Scripts/model/i18n/gr.ts
- src/Scripts/model/i18n/it.ts
- src/Scripts/model/i18n/nl.ts
- src/Scripts/model/i18n/pl.ts
- src/Scripts/model/i18n/pt.ts
- src/Scripts/model/i18n/ru.ts
- src/Scripts/model/i18n/tr.ts
- src/Scripts/model/i18n/zh.ts
> Change "First Day of the Fiscal Year"

- src/Infrastructure/AppWindow.cs
- src/Infrastructure/Helpers/TelemetryHelper.cs
- src/Infrastructure/Security/CredentialDialog.cs
- src/Infrastructure/Services/WebProxyWrapper.cs
- Handled WebView2 BasicAuthenticationRequested to support proxy auth for telemetry requests
- Fixed CredentialDialog unmanaged memory disposition
> Added support for custom credentials to HttpSystemProxy

- src/Assets/ManageDates/Templates/HolidaysDefinition.json
- src/Scripts/model/dates.ts
Changes copied from https://github.com/sql-bi/Bravo/pull/444
> Added Chinese holidays

- src/Bravo.csproj
- src/Infrastructure/Helpers/ConnectionStringHelper.cs
Opt-out and use NLS instead of ICU globalization APIs
> Removed the LocaleIdentifier workaround in the connection string

- src/Scripts/model/i18n/locales.ts
Added as requested from code review in #531
> Add Persian to locale.ts

- src/Bravo.csproj
Updated packages (and DaxTemplate in particular) to implement a workaround for a SWITCH bug introduced in Power BI Service.
> Workaround for SWITCH bug in Power BI Service

- src/Assets/ManageDates/Templates/DateLocalization-01.json
- src/Assets/ManageDates/Templates/DateLocalization-02.json
- src/Assets/ManageDates/Templates/DateLocalization-03.json
- src/Assets/ManageDates/Templates/DateLocalization-04.json
- src/Assets/ManageDates/Templates/DateLocalization-05.json
- src/Assets/ManageDates/Templates/DateLocalization-06.json
- src/Assets/ManageDates/Templates/DateLocalization-07.json
As suggested in @albertospelta 's answer to #563 I have added Danish translation for date table columns. I have translated column names in all DateLocalization files. Br, Niels
> Added DateLocalization for Danish

- src/Infrastructure/Extensions/HostingExtensions.cs
- src/Startup.cs
Allow any method/header/origin
> CORS allow any origin, using default policy

- src/Infrastructure/AppInstance.cs
- Removing custom ACL from `NamedPipeServer`
- Revert to `PipeOptions.CurrentUserOnly` instead of using custom `PipeSecurity`/`PipeAccessRule`
> Add support to run Bravo on multi-session/run-as scenarios

- src/Infrastructure/Configuration/Settings/StartupSettings.cs
- src/Infrastructure/Messages/AppInstanceStartupMessage.cs
Add output StartupSettings.commandLineErrors error messages
> Fix command line args parsing error

- src/Bravo.csproj
Using transitive dependency from TOM
> Remove direct dependency on Microsoft.Identity.Client

- src/Bravo.csproj
Using TOM transitive dependency from VPAX library
> Remove TOM package reference

- test/Bravo.Tests/Bravo.Tests.csproj
- Microsoft.NET.Test.Sdk version 17.6.3
- xunit version 2.5.0
- coverlet.collector version 6.0.0
> Bump xunit, coverlet, MS test SDK

- src/Bravo.csproj
- test/Bravo.Tests/Bravo.Tests.csproj
- Microsoft.Extensions.Logging.ApplicationInsights version 2.22.0
- Update test packages
> Bump Dax.Template version 0.1.10

- src/Models/AnalyzeModel/TabularMeasure.cs
- src/Services/FormatDaxService.cs
> Fix error formatting measures with empty expressions
