sql-bi/Bravo

- installer/wix/src/Bravo/Bravo-perUser.wxs
- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/AppWindow.cs
- src/Infrastructure/Configuration/UserPreferences.cs
- src/Infrastructure/Helpers/CommonHelper.cs
- The update file to be downloaded is identified according to the app deployment type (perUser/perMachine/frameworkdependant/etc)
- Added the string suffix _(User)_ to the app name in the control panel and to the menu shortcut when the distribution type is "perUser".
> Download updates according to app type

- src/Infrastructure/Configuration/UserPreferences.cs
TelemetryEnabled does not update correctly from the 'applicationTelemetryEnableValue' registry setting
> Fix TelemetryEnabled does not honor registry setting

- src/Assets/ManageDates/Templates/HolidaysDefinition.json
Hi, I have added Japanese holidays to HolidaysDefinition.json. Please enable "Bravo" to output Japanese holidays table as well.
However, there are two complicated setup days for Japanese holidays. This is because the length of the day and night are calculated and set as holidays every year. The dates change. The formula in Excel and the URL to check the list of dates are attached below.
Vernal Equinox Day → March
The date can be obtained in Excel using the following formula.
INT(20.8431+0.242194*([Current Year]-1980))-INT((([Current Year]-1980)/4)
Autumnal Equinox Day → September
The date can be found in Excel using the following formula.
INT(23.2488+0.242194*([Current Year]-1980))-INT((([Current Year]-1980)/4)
Currently, the dates are set to 21 March and 23 September.
Bravo is a great …
> Additional Japanese holidays.

- src/Infrastructure/Extensions/HostingExtensions.cs
Exception handled as BravoProblem.SignInMsalExceptionOccurred because the AMO inner exception is a MsalClientException
> Handled AMO.AuthenticationException authentication_canceled

- installer/wix/src/Bravo/Bravo.xslt
To fix a WiX/MSI bug that causes the file to be removed and not reinstalled when a downgrade is detected during a MSI upgrade.
Previously the only solution is to completely uninstall and then reinstall.
> Installer - fix library downgrade during a MSI upgrade

- src/Infrastructure/Services/ConnectionWrapper.cs
- src/Models/FormatDax/FormatDaxResponse.cs
- src/Services/FormatDaxService.cs
A `NullReferenceException` is raised instead of a `TOMDatabaseDatabaseNotFound` error
> Fix NullReferenceException/TOMDatabaseDatabaseNotFound

- src/Infrastructure/AppEnvironment.cs
The PBIDesktop window title does not always contain the spacing character before and after the separator character
> Fix spacing char in PBIDesktop.MainWindowTitle suffix

- src/Services/ExportDataService.cs
Milliseconds are always zeroed out when exporting to CSV
> Fix issue where exporting DateTime column to CSV removes milliseconds

- src/Infrastructure/Helpers/ConnectionStringHelper.cs
- src/Models/PBICloudDataset.cs
Use `OleDbConnectionStringBuilder.DataSource` property to get the server name instead of using the hardcoded "Data Source" key.
> Add ConnectionStringHelper.GetConnectionStringProperties

- src/Infrastructure/Helpers/ConnectionStringHelper.cs
- src/Infrastructure/Models/PBICloud/PBICloudEnvironment.cs
- src/Models/PBICloudDataset.cs
Add 'Identity Provider' and enable 'Persist Security Info' in `PBICloudDataset` connection string
> Add 'Identity Provider' to PBICloudDataset connection string

- src/Infrastructure/Helpers/VpaxToolsHelper.cs
Throw `VpaxFileImportError` in case the Vpax archive is invalid (i.e. `DaxModel` is null)
> Throw VpaxFileImportError in case Vpax.DaxModel is null

- src/Infrastructure/AppEnvironment.cs
- test/Bravo.Tests/Infrastructure/Extensions/StringExtensionsTests.cs
Support Latvian(`lv`) language where `NBSP` char is used instead of whitespace
> Add new suffix to PBIDesktopMainWindowTitleSuffixes

- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/Extensions/ProcessExtensions.cs
- src/Infrastructure/Extensions/StringExtensions.cs
- test/Bravo.Tests/Infrastructure/Extensions/StringExtensionsTests.cs
Always return the PBID windowTitle instead of returning null when the suffix ` - Power BI Desktop` is not present.
> Always return the windowTitle in case the PBID suffix does not exists

- src/Bravo.csproj
Removing the globalization APIs opt-out workaround since the related issues have been fixed in TOM libs.
See https://github.com/sql-bi/Bravo/issues/324#issuecomment-1203624655 and https://github.com/sql-bi/Bravo/pull/464
> Remove Globalization.UseNls runtime host config

- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/Extensions/DataReaderExtensions.cs
- src/Infrastructure/Extensions/EnumerableExtensions.cs
- src/Infrastructure/Services/ConnectionWrapper.cs
- src/Models/DiagnosticMessage.cs
- src/Models/ExportData/ExportDataEntity.cs
- src/Services/ExportDataService.cs
Row batches are sorted based on the `ROWNUMBER` column. Refreshing the table data can modify the `ROWNUMBER` values, impacting the sorting order of the rows.
> Add support for exporting data in row batch mode

- .azure/pipelines/build-bravo.yaml
- .azure/pipelines/release-bravo.yaml
Pinned to latest version compatible with .NET 6.0
> Pin AzureSignTool version in yaml pipelines

- src/Services/ExportDataService.cs
Fixes an `ArgumentOutOfRangeException` occurring when attempting to export data to XLSX format from an empty table.
> Fix error when exporting data to XLSX from an empty table

- src/Assets/ManageDates/Templates/HolidaysDefinition.json
In 2007, Greenery Day moved to May 4, and April 29 was changed to Shōwa Day in accordance with a 2005 revision of the law pertaining to public holidays. This fixes an issue where duplicate rows caused the `LOOKUPVALUE` function to fail with the error "A table of multiple values was supplied where a single value was expected" while retrieving the noliday name.
> Fix JP/Greenery Day holiday definition

- src/Controllers/ExportDataController.cs
- src/Services/ExportDataService.cs
Zip64 is an experimental feature in Bravo that must be explicitly enabled by the user and is not enabled by default because it may create a file that Excel or LibreOffice reports as corrupt.
> Add experimental flag to enable ZIP64 for exporting to Excel

- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/AppWindow.cs
Enable the DevTools in non-stable releases when the `Shift` key is pressed
> Enable DevTools for troubleshooting in non-stable releases

- src/Assets/ManageDates/Templates/HolidaysDefinition.json
- Arbejdernes kampdag
- Grundlovsdag
- Juleaftensdag
- Nytårsaftensdag
> Remove non-official Danish holidays from JSON definition

- src/Bravo.csproj
- src/Infrastructure/Helpers/MsalHelper.cs
- test/Bravo.Tests/Bravo.Tests.csproj
This update addresses a breaking change in the `Microsoft.Identity.Client` library, which has removed support for the `net6.0-windows7.0` binary. To maintain compatibility for desktop applications targeting `net6.0-windows`, the `Microsoft.Identity.Client.Desktop` dependency has been added. This change ensures that authentication using a browser, with the method `WithWindowsEmbeddedBrowserSupport()`, continues to work seamlessly. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4468
Additionally, this update allows us to remove the dependency on the `Microsoft.Windows.SDK` framework, which has resulted in a reduction of installed binary sizes.
> Retarget framework from `net6-windows10.0.17763.0` to `net6-windows`

- installer/wix/src/Bravo/Bravo.xslt
This fixes a build error introduced in https://github.com/sql-bi/Bravo/pull/849 (https://github.com/sql-bi/DaxFormatter/pull/17) where `System.Text.Json.dll` is no longer a transitive dependency, as it is now used for the `netstandard2.0` target framework.
> Remove System.Text.Json.dll references from Bravo.xslt

- .azure/pipelines/build-bravo.yaml
- .github/workflows/ci.yml
- global.json
- src/Bravo.csproj
- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/AppWindow.cs
- src/Infrastructure/Authentication/AppAuthenticationHandler.cs
- src/Infrastructure/Extensions/HostingExtensions.cs
- src/Infrastructure/Helpers/CommonHelper.cs
- test/Bravo.Tests/Bravo.Tests.csproj
Enable multi-targeting in build configuration to support `.NET 8`
- `global.json`: Updated to use .NET SDK version `8.0.400`.
- `Bravo.csproj`: Targeted both `net6-windows` and `net8-windows` frameworks, updated `System.Management` package reference.
> Add support for NET 8

- src/Scripts/package-lock.json
- src/Scripts/package.json
Changed the `json-formatter-js` dependency from a GitHub repository link to a specific version (`^2.5.23`) in both `package.json` and `package-lock.json`.
> Update json-formatter-js dependency to use NPM package

- src/Infrastructure/Extensions/HostingExtensions.cs
Enhance error tracing by logging all exception types. When in verbose mode, exception details are always logged using `AppEnvironment.AddDiagnostics()`, improving observability and aiding in debugging and monitoring.
> Ensure all host exceptions are logged in verbose mode

- src/Bravo.csproj
This pull request updates several NuGet package dependencies in the `Bravo.csproj` file to newer versions.
Dependency upgrades:
* Upgraded `Dax.Model.Extractor` from version 1.9.0 to 1.11.0 for enhanced model extraction capabilities.
* Upgraded `Dax.ViewModel` from version 1.9.0 to 1.11.0 for improved view model support.
* Upgraded `Dax.Vpax` from version 1.9.0 to 1.11.0 for better VPAX file handling.
* Upgraded `Dax.Vpax.Obfuscator` from version 1.1.3 to 1.2.1 for improved obfuscation features.
> Bump VPAX version 1.11.0, Obfuscator 1.2.1

- src/Infrastructure/AppEnvironment.cs
- src/Infrastructure/Helpers/CommonHelper.cs
Introduced a method `AddEnvironmentDiagnosticInfo` to collect and log environment-related diagnostics. Updated `CommonHelper.cs` to log diagnostic information during the update check process. This applies only when verbose diagnostics are enabled.
> Enhance diagnostics with environment and update info

- src/Bravo.csproj
Fixes a bug introduced in version 1.0.10 that causes the application to crash and close when attempting to connect to a local PBI Desktop model.
> Fix crash when connecting to a local PBI Desktop
